2021-01-09 15:46:38,221 - WARNING - weibo.py[:103] - since_date值应为yyyy-mm-dd形式或整数,请重新输入
2021-01-09 20:38:20,276 - ERROR - weibo.py[:1093] - 'id'
Traceback (most recent call last):
  File "weibo.py", line 1062, in get_pages
    self.print_user_info()
  File "weibo.py", line 577, in print_user_info
    logger.info(u'用户id：%s', self.user['id'])
KeyError: 'id'
2021-01-09 20:38:29,186 - ERROR - weibo.py[:1093] - 'id'
Traceback (most recent call last):
  File "weibo.py", line 1062, in get_pages
    self.print_user_info()
  File "weibo.py", line 577, in print_user_info
    logger.info(u'用户id：%s', self.user['id'])
KeyError: 'id'
2021-01-09 20:40:19,726 - ERROR - weibo.py[:1093] - 'id'
Traceback (most recent call last):
  File "weibo.py", line 1062, in get_pages
    self.print_user_info()
  File "weibo.py", line 577, in print_user_info
    logger.info(u'用户id：%s', self.user['id'])
KeyError: 'id'
2021-01-09 20:41:05,274 - ERROR - weibo.py[:1093] - 'id'
Traceback (most recent call last):
  File "weibo.py", line 1062, in get_pages
    self.print_user_info()
  File "weibo.py", line 577, in print_user_info
    logger.info(u'用户id：%s', self.user['id'])
KeyError: 'id'
2021-01-09 20:46:22,568 - ERROR - weibo.py[:1093] - 'id'
Traceback (most recent call last):
  File "weibo.py", line 1062, in get_pages
    self.print_user_info()
  File "weibo.py", line 577, in print_user_info
    logger.info(u'用户id：%s', self.user['id'])
KeyError: 'id'
2021-01-09 20:51:10,073 - ERROR - weibo.py[:1093] - 'id'
Traceback (most recent call last):
  File "weibo.py", line 1062, in get_pages
    self.print_user_info()
  File "weibo.py", line 577, in print_user_info
    logger.info(u'用户id：%s', self.user['id'])
KeyError: 'id'
2021-01-09 20:59:37,282 - ERROR - weibo.py[:1093] - 'id'
Traceback (most recent call last):
  File "weibo.py", line 1062, in get_pages
    self.print_user_info()
  File "weibo.py", line 577, in print_user_info
    logger.info(u'用户id：%s', self.user['id'])
KeyError: 'id'
